# Generated by Django 6.1 on 2026-08-13 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('distributions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='milkdelivery',
            constraint=models.UniqueConstraint(fields=('customer', 'ethiopian_year', 'ethiopian_month', 'ethiopian_day'), name='unique_customer_delivery_per_day'),
        ),
    ]
