# Generated by Django 6.1 on 2026-08-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FUEL', 'Fuel'), ('WORKER_PAYMENT', 'Worker Payment'), ('TRANSPORTATION', 'Transportation'), ('VEHICLE_MAINTENANCE', 'Vehicle Maintenance'), ('PACKAGING', 'Packaging'), ('ELECTRICITY', 'Electricity'), ('PROCESSING', 'Processing'), ('RENT', 'Rent'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ethiopian_date', models.CharField(max_length=20)),
                ('ethiopian_year', models.IntegerField(default=0)),
                ('ethiopian_month', models.IntegerField(default=0)),
                ('ethiopian_day', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('related_activity', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
