# Generated by Django 6.1 on 2026-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='settlement_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settlements.settlementperiod'),
        ),
    ]
