# Generated by Django 6.1 on 2026-08-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethiopian_date', models.CharField(help_text='e.g. Meskerem 5, 2017', max_length=20)),
                ('ethiopian_year', models.IntegerField()),
                ('ethiopian_month', models.IntegerField()),
                ('ethiopian_day', models.IntegerField()),
                ('morning_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('evening_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_quantity', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, help_text='Locked price per liter at collection time', max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='suppliers.supplier')),
            ],
        ),
    ]
