# Generated by Django 6.1 on 2026-08-13 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_collections', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='milkcollection',
            constraint=models.UniqueConstraint(fields=('supplier', 'ethiopian_year', 'ethiopian_month', 'ethiopian_day'), name='unique_supplier_collection_per_day'),
        ),
    ]
