# Generated by Django 6.1 on 2026-08-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethiopian_year', models.IntegerField()),
                ('ethiopian_month', models.IntegerField()),
                ('period_number', models.IntegerField(help_text='1 for days 1-15, 2 for 16-end')),
                ('start_date_ethiopian', models.CharField(max_length=20)),
                ('end_date_ethiopian', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CALCULATED', 'Calculated'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('SETTLED', 'Settled'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_delivered', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='customers.customer')),
                ('settlement_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_settlements', to='settlements.settlementperiod')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_milk_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('settlement_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_settlements', to='settlements.settlementperiod')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='suppliers.supplier')),
            ],
        ),
    ]
