# Generated by Django 6.1 on 2026-08-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milk_inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkWastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethiopian_date', models.CharField(max_length=20)),
                ('ethiopian_year', models.IntegerField()),
                ('ethiopian_month', models.IntegerField()),
                ('ethiopian_day', models.IntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Amount of milk wasted in liters', max_digits=10)),
                ('reason', models.CharField(choices=[('SPOILED', 'Spoiled/Sour'), ('SPILLED', 'Spilled/Leaked'), ('CONTAMINATED', 'Contaminated'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
